'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowDown,ArrowLeft,ArrowRight,ArrowUp,ArrowUpRight,BookOpen,Briefcase,Coffee,Compass,Film,Gamepad2,Home,Map,Moon,Radio,RotateCcw,Settings2,Sun,Volume2,VolumeX,X,ChevronLeft,ChevronRight,ExternalLink} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '@/components/ui/dialog';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {locations,type Input} from '@/lib/world/driving';
import {content} from '@/lib/world/content';
import {combineTouchInput} from '@/lib/world/touch-input';
import type{WorldApi,WorldHud}from '@/lib/world/scene';
const icons={about:Home,works:Film,career:Briefcase,lab:Gamepad2,learn:BookOpen,coffee:Coffee,radar:Radio};
export function DrivingWorld(){
 const root=useRef<HTMLDivElement>(null),canvas=useRef<HTMLCanvasElement>(null),api=useRef<WorldApi|null>(null);
 const[ready,setReady]=useState(false),[error,setError]=useState(false),[intro,setIntro]=useState(true),[mapOpen,setMapOpen]=useState(false),[panel,setPanel]=useState<string|null>(null),[showcase,setShowcase]=useState<string|null>(null),[projectId,setProjectId]=useState('aigc-portal'),[low,setLow]=useState(false),[night,setNight]=useState(false),[sound,setSound]=useState(false),[visited,setVisited]=useState<string[]>([]);
 const[hud,setHud]=useState<WorldHud>({speed:0,nearby:null,position:{x:0,z:7},labels:[],drivingTo:false});
 const[touchMode,setTouchMode]=useState(false);
 const heldPointers=useRef(new globalThis.Map<number,Partial<Input>>());
 const[touchInput,setTouchInput]=useState<Input>({throttle:0,steer:0,brake:false});
 function publishTouchInput(){const input=combineTouchInput(heldPointers.current.values());setTouchInput(input);api.current?.setInput(input);}
 function clearTouchInput(){heldPointers.current.clear();publishTouchInput();}
 useEffect(()=>{
  const coarse=matchMedia('(pointer: coarse)'),noHover=matchMedia('(hover: none)');
  const detect=()=>setTouchMode(coarse.matches||(navigator.maxTouchPoints>0&&noHover.matches));
  detect();coarse.addEventListener('change',detect);noHover.addEventListener('change',detect);
  addEventListener('blur',clearTouchInput);document.addEventListener('visibilitychange',clearTouchInput);
  return()=>{coarse.removeEventListener('change',detect);noHover.removeEventListener('change',detect);removeEventListener('blur',clearTouchInput);document.removeEventListener('visibilitychange',clearTouchInput);};
 },[]);
 useEffect(()=>{clearTouchInput();},[panel,mapOpen,showcase,touchMode]);
 const openRef=useRef<(id:string)=>void>(()=>{});
 const remember=(id:string)=>setVisited(v=>{const next=v.includes(id)?v:[...v,id];try{localStorage.setItem('piguannan-discovered',JSON.stringify(next));}catch{}return next;});
 openRef.current=id=>{setIntro(false);remember(id);if(id==='works'||id==='learn'){const first=content.projects.find(p=>p.category===id)!;setProjectId(first.id);setShowcase(id);setPanel(null);api.current?.setShowcase(id,first.id);}else{setShowcase(null);api.current?.setShowcase(null);setPanel(id);}};
 useEffect(()=>{let live=true;try{const ids=JSON.parse(localStorage.getItem('piguannan-discovered')||'[]');if(Array.isArray(ids))setVisited(ids.filter(id=>locations.some(p=>p.id===id)));}catch{}
  import('@/lib/world/scene').then(async({createWorld})=>{if(!live||!canvas.current)return;try{const instance=await createWorld(canvas.current,state=>{if(live)setHud(state);},id=>openRef.current(id));if(!live){instance.dispose();return;}api.current=instance;instance.setQuality(false);setReady(true);}catch(e){console.error('World renderer failed',e);setError(true);}}).catch(()=>setError(true));return()=>{live=false;api.current?.dispose();api.current=null;};
 },[]);
 useEffect(()=>{api.current?.setPaused(!!panel||mapOpen||!!showcase);},[ready,panel,mapOpen,showcase]);
 useEffect(()=>{api.current?.setQuality(low);},[low]);useEffect(()=>{api.current?.setNight(night);},[night]);
 const close=()=>{clearTouchInput();setPanel(null);setShowcase(null);api.current?.setShowcase(null);requestAnimationFrame(()=>canvas.current?.focus());};
 const go=(id:string)=>{clearTouchInput();setMapOpen(false);setIntro(false);setPanel(null);setShowcase(null);api.current?.setShowcase(null);api.current?.setPaused(false);api.current?.goTo(id);canvas.current?.focus();};
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.closest('input,textarea,[contenteditable="true"],[role="dialog"]'))return;if(e.code==='KeyR')clearTouchInput();if(e.code==='KeyM'&&!panel&&!showcase&&!e.repeat){e.preventDefault();setMapOpen(v=>!v);}if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','KeyB'].includes(e.code)){setTouchMode(false);setIntro(false);}if(e.code==='Escape'&&showcase)close();if(e.code==='KeyF'&&!panel&&!mapOpen){if(document.fullscreenElement)void document.exitFullscreen();else void root.current?.requestFullscreen().catch(()=>{});}};addEventListener('keydown',handler);return()=>removeEventListener('keydown',handler);},[ready,panel,mapOpen,showcase]);
 const nearby=locations.find(p=>p.id===hud.nearby),active=locations.find(p=>p.id===panel);const project=content.projects.find(p=>p.id===projectId)!;
 const exhibition=content.projects.filter(p=>p.category===showcase),index=exhibition.findIndex(p=>p.id===projectId);
 function selectProject(id:string){setProjectId(id);if(showcase)api.current?.setShowcase(showcase,id);}
 function pad(input:Partial<Input>){
  const release=(e:React.PointerEvent<HTMLButtonElement>)=>{heldPointers.current.delete(e.pointerId);publishTouchInput();};
  return{
   onPointerDown:(e:React.PointerEvent<HTMLButtonElement>)=>{if(e.button!==0)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);heldPointers.current.set(e.pointerId,input);publishTouchInput();},
   onPointerUp:release,onPointerCancel:release,onLostPointerCapture:release,
   onContextMenu:(e:React.MouseEvent)=>e.preventDefault(),
  };
 }

 const openDetail=(id:string)=>{setProjectId(id);setPanel('project');};
 function cards(category:string){return<div className="studio-projects">{content.projects.filter(p=>p.category===category).map(p=><button key={p.id} onClick={()=>openDetail(p.id)}>{p.image&&<img src={p.image} alt={`${p.title}实际页面`} loading="lazy"/>}<div><small>{p.status}</small><strong>{p.title}</strong><p>{p.description}</p><span>查看项目 <ArrowUpRight size={15}/></span></div></button>)}</div>;}
 return<div ref={root} data-input-mode={touchMode?'touch':'keyboard'} onPointerDownCapture={e=>{if(e.pointerType==='touch')setTouchMode(true);}} className={`driving-world studio-world ${touchMode?'is-touch':'is-keyboard'} ${night?'is-night':''} ${intro&&ready?'is-intro':''} ${showcase?'is-viewing':''}`}>
  <canvas className="world-canvas" ref={canvas} tabIndex={0} aria-label={touchMode?"冠南的片场。用屏幕方向按钮驾驶，可双指同时前进和转向。按停刹车，点地点查看内容，拖动画面调整视角。":"冠南的片场。WASD或方向键驾驶，空格跳跃，B刹车，E或回车进入附近地点，R复位，M地图。拖动平移视角，滚轮缩放。"}/>
  <header className="drive-header"><a href="#" className="drive-brand" onClick={e=>{e.preventDefault();close();api.current?.reset();}}><span>π</span><div>冠南的片场<small>FILM · PRODUCT · AI</small></div></a><div className="drive-toolbar"><button className="map-toggle" onClick={()=>setMapOpen(true)} aria-label="打开探索地图"><Map size={18}/><span>地图</span>{!touchMode&&<kbd>M</kbd>}</button><button aria-label={sound?'关闭声音':'开启声音'} title={sound?'关闭声音':'开启声音'} onClick={()=>{api.current?.setSound(!sound);setSound(v=>!v);}}>{sound?<Volume2 size={18}/>:<VolumeX size={18}/>}</button><button aria-label={night?'切换白天':'切换夜晚'} onClick={()=>setNight(v=>!v)}>{night?<Sun size={18}/>:<Moon size={18}/>}</button><button aria-label={low?'开启精细画质':'开启流畅画质'} aria-pressed={low} onClick={()=>setLow(v=>!v)}><Settings2 size={18}/></button><button aria-label="回到起点" onClick={()=>{close();api.current?.reset();}}><RotateCcw size={18}/></button></div></header>
  {!ready&&!error&&<div className="world-loading"><Compass size={30}/><strong>片场正在准备</strong><span>布光、搭景，让想法有处落地。</span></div>}
  {error&&<div className="world-loading error"><strong>可以先从内容地图开始</strong><p>当前浏览器暂时无法呈现 3D 场景。</p><button onClick={()=>setMapOpen(true)}>打开内容地图 <ArrowRight size={17}/></button></div>}
  {ready&&!intro&&!showcase&&<div className="place-labels">{hud.labels.filter(p=>p.visible).map(point=>{const place=locations.find(p=>p.id===point.id)!;return<button key={place.id} className={`place-label studio-pin ${hud.nearby===place.id?'is-near':''}`} style={{left:point.x,top:point.y}} onClick={()=>openRef.current(place.id)} aria-label={`查看${place.name}`}><i className="pin-diamond"/><span>{place.name}</span>{!touchMode&&<kbd>↵</kbd>}</button>;})}</div>}
  {intro&&ready&&<aside className="studio-intro"><span className="drive-eyebrow">WELCOME TO MY LITTLE SET</span><h1>你好，我是冠南。</h1><p>从产品、影院到 AI。<br/>来看看我的履历、作品和开源实验。</p><button id="start-world" onClick={()=>{setIntro(false);canvas.current?.focus();}}>进入片场 <ArrowRight size={18}/></button><small>{touchMode?"按住屏幕方向键驾驶 · 双指前进转弯":"WASD / 方向键驾驶 · M 打开地图"}</small></aside>}
  {!intro&&!showcase&&<>{!touchMode&&<div className="studio-instructions"><kbd>WASD / ↑↓←→</kbd> 驾驶 <span>·</span><kbd>SPACE</kbd> 跳跃 <span>·</span><kbd>B</kbd> 刹车</div>}<div className="studio-progress"><span>{visited.length} / {locations.length}</span> 片场足迹</div></>}
  {nearby&&!intro&&!showcase&&!panel&&<button className="enter-place" onClick={()=>openRef.current(nearby.id)}><span className="enter-key">{touchMode?"查看":"↵"}</span><span><small>走近一个故事</small><strong>{nearby.name}</strong></span><ArrowUpRight size={20}/></button>}
  {touchMode&&ready&&!intro&&!showcase&&!panel&&!mapOpen&&<div className="touch-drive" role="group" aria-label="触屏驾驶控制">
   <button aria-label="前进" aria-pressed={touchInput.throttle>0} className="touch-up" {...pad({throttle:1})}><ArrowUp/></button>
   <button aria-label="左转" aria-pressed={touchInput.steer<0} className="touch-left" {...pad({steer:-1})}><ArrowLeft/></button>
   <button aria-label="倒车" aria-pressed={touchInput.throttle<0} className="touch-down" {...pad({throttle:-1})}><ArrowDown/></button>
   <button aria-label="右转" aria-pressed={touchInput.steer>0} className="touch-right" {...pad({steer:1})}><ArrowRight/></button>
   <button aria-label="刹车" aria-pressed={touchInput.brake} className="touch-brake" {...pad({brake:true})}>停</button>
   <small className="touch-drive-hint">按住驾驶 · 双指转弯</small>
  </div>}
  {showcase&&<section className="showcase-ui" aria-label="场景内的作品阅读"><button className="showcase-exit" onClick={close}><X size={17}/> 回到片场</button><div className="showcase-detail"><small>{project.status}</small><h2>{project.title}</h2><p>{project.description}</p><ul>{project.features.map(f=><li key={f}>{f}</li>)}</ul>{project.attribution&&<p className="project-credit">{project.attribution}</p>}<div className="project-links">{project.url&&<a href={project.url} target="_blank" rel="noreferrer">{project.cta} <ArrowUpRight size={16}/></a>}{project.repo&&<a href={project.repo} target="_blank" rel="noreferrer">源代码 <ExternalLink size={14}/></a>}</div><div className="showcase-nav"><button aria-label="上一项作品" onClick={()=>selectProject(exhibition[(index-1+exhibition.length)%exhibition.length].id)}><ChevronLeft/></button><span>{index+1} / {exhibition.length}</span><button aria-label="下一项作品" onClick={()=>selectProject(exhibition[(index+1)%exhibition.length].id)}><ChevronRight/></button></div>{showcase==='learn'&&<details className="teaching-shelf"><summary>全部课程与学习资料</summary>{content.teaching.map(t=><a key={t.id} href={t.href} target="_blank" rel="noreferrer"><strong>{t.title}</strong>{'attribution' in t&&<small>{t.attribution}</small>}</a>)}</details>}</div></section>}
  <Dialog open={mapOpen} onOpenChange={setMapOpen}><DialogContent className="world-dialog studio-map-dialog" showCloseButton={false}><div className="world-dialog-top"><span>PI GUANNAN / EXPLORE</span><button aria-label="关闭地图" onClick={()=>setMapOpen(false)}><X size={21}/></button></div><DialogTitle className="world-dialog-title">这里，每一站都有来处。</DialogTitle><DialogDescription className="world-dialog-description">履历、项目、开源实验与日常生活。你可以到现场，也可以直接阅读。</DialogDescription><div className="studio-map-grid"><div className="studio-map-art"><svg viewBox="-42 -42 84 84" aria-hidden="true"><rect x="-42" y="-42" width="84" height="84" rx="7" fill="#75989d"/><path d="M-36 -31L-20 -38L0 -36L21 -37L35 -23L37 -1L34 22L20 36L-3 37L-28 32L-37 13L-39 -10Z" fill="#d8bc8c"/><path d="M0 7L-17 -10L16 -13L28 4L14 25L-12 25L0 7L28 4M0 7H-25" fill="none" stroke="#f1dfb5" strokeWidth="2.4"/>{locations.map((p,i)=><g key={p.id}><circle cx={p.x} cy={p.z} r="3" fill={p.color}/><text x={p.x} y={p.z+1.1} textAnchor="middle" fontSize="3" fill="white">{i+1}</text></g>)}<circle cx={hud.position.x} cy={hud.position.z} r="1.3" fill="#355d73" stroke="white" strokeWidth=".5"/></svg></div><div className="destination-list">{locations.map((p,i)=>{const Icon=icons[p.id];return<div key={p.id}><span className="destination-icon" style={{background:p.color}}><Icon size={23}/></span><div><small>0{i+1} / {p.label}</small><strong>{p.name}</strong></div><div className="destination-actions"><button disabled={!ready} onClick={()=>go(p.id)}>到现场</button><button onClick={()=>{setMapOpen(false);if(!ready&&(p.id==='works'||p.id==='learn'))setPanel(p.id);else openRef.current(p.id);}}>直接阅读 <ArrowUpRight size={13}/></button></div></div>;})}</div></div></DialogContent></Dialog>
  <Dialog open={!!panel} onOpenChange={open=>{if(!open)close();}}><DialogContent className="world-dialog content-dialog" showCloseButton={false}><div className="world-dialog-top"><span>{panel==='project'?'PROJECT FILE':active?.label}</span><button aria-label="关闭内容，继续探索" onClick={close}><X size={21}/></button></div><DialogTitle className="world-dialog-title">{panel==='project'?project.title:active?.name}</DialogTitle><DialogDescription className="world-dialog-description">{panel==='about'?content.identity.philosophy:panel==='career'?'从电子信息工程，到产品、增长、影视与 AI。':panel==='lab'?'代码是实验留下的另一种记录。':panel==='radar'?'把线索、原文和核验状态放在一起。':panel==='coffee'?'生活里的小问题，也值得认真做一个工具。':panel==='project'?project.status:''}</DialogDescription>
   {panel==='about'&&<div className="place-content profile-content"><img src="/world/avatar.png" alt="冠南原站的蓝白围巾数字形象"/><h3>李冠南 <small>LI GUANNAN</small></h3><p>{content.identity.headline}</p><p>产品经理 · 生成式 AI 应用 · 影视数字化<br/>浙江 · 横店</p><div className="world-chips">{content.skills.slice(0,5).map(s=><span key={s.id}>{s.title}</span>)}</div><details className="skill-details"><summary>能力与工具</summary>{content.skills.map(s=><div key={s.id}><strong>{s.title}</strong><p>{s.items.join(' · ')}</p></div>)}</details><div className="profile-links"><a href="https://github.com/Liguannan-Alex" target="_blank" rel="noreferrer">GitHub ↗</a><a href="mailto:liguannan793304900@gmail.com">Email ↗</a><a href="https://piguannan.com/classic/" target="_blank" rel="noreferrer">经典主页 ↗</a></div><div className="wechat-card"><img src="/world/wechat-qr.png" alt="公众号 π·冠南 二维码"/><p>公众号「π·冠南」<small>AI · 认知 · 影视</small></p></div><details className="world-credits"><summary>关于这个世界与开源致谢</summary><p>内容与空间围绕冠南的公开履历和项目制作。车辆模型与树叶纹理来自 Bruno Simon 的 MIT 开源作品；底层使用 Three.js 与 Rapier。</p><a href="/world/BRUNO-MIT-LICENSE.txt" target="_blank" rel="noreferrer">查看资源许可 ↗</a></details></div>}
   {panel==='career'&&<div className="career-list">{content.career.map((c,i)=><article key={i}><time>{c.year}</time><div><h3>{c.title}</h3><small>{c.place}</small><p>{c.description}</p></div></article>)}</div>}
   {panel==='lab'&&<Tabs defaultValue="projects"><TabsList className="studio-tabs"><TabsTrigger value="projects">游戏与实验</TabsTrigger><TabsTrigger value="repositories">全部仓库 · {content.repositories.length}</TabsTrigger></TabsList><TabsContent value="projects">{cards('lab')}</TabsContent><TabsContent value="repositories"><div className="repo-list">{content.repositories.map(r=><a key={r.name} href={r.url} target="_blank" rel="noreferrer"><strong>{r.name==='-'?'既要又要还要':r.name}<ArrowUpRight size={15}/></strong><p>{r.description}</p><small>{r.language} · 更新于 {r.updated}</small></a>)}</div></TabsContent></Tabs>}
   {(panel==='radar'||panel==='coffee'||panel==='works'||panel==='learn')&&cards(panel)}
   {panel==='learn'&&<div className="teaching-links">{content.teaching.map(t=><a key={t.id} href={t.href} target="_blank" rel="noreferrer">{t.title}<ArrowUpRight size={15}/></a>)}</div>}
   {panel==='project'&&<div className="place-content project-file">{project.image&&<img src={project.image} alt={`${project.title}实际页面`}/>}<p>{project.description}</p><ul>{project.features.map(f=><li key={f}>{f}</li>)}</ul>{project.attribution&&<p className="project-credit">{project.attribution}</p>}<div className="project-links">{project.url&&<a href={project.url} target="_blank" rel="noreferrer">{project.cta}<ArrowUpRight size={16}/></a>}{project.repo&&<a href={project.repo} target="_blank" rel="noreferrer">查看源代码<ArrowUpRight size={16}/></a>}</div></div>}
   <button className="back-to-world" onClick={close}>继续逛逛 <ArrowRight size={16}/></button>
  </DialogContent></Dialog>
 </div>;
}
