import * as THREE from 'three';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';
import { locations, type Input, type Point } from './driving';
import { createVehiclePhysics, WHEEL_ANCHORS } from './physics';
import { makeEnvironment } from './environment';
import { careerEntries, findNearbyCareer, normalizeCareerIndex } from './career';

export type WorldHud={speed:number;nearby:string|null;position:Point;labels:{id:string;x:number;y:number;visible:boolean}[];drivingTo:boolean;contactCount?:number;bodyY?:number;careerIndex?:number|null;careerLabels?:{index:number;x:number;y:number;visible:boolean}[]};
export type WorldApi={reset:()=>void;goTo:(id:string)=>void;setInput:(input:Partial<Input>)=>void;setPaused:(value:boolean)=>void;setQuality:(low:boolean)=>void;setNight:(value:boolean)=>void;setShowcase:(id:string|null,projectId?:string)=>void;setSound:(on:boolean)=>void;setCareer:(index:number|null)=>void;dispose:()=>void};
declare global{interface Window{render_game_to_text?:()=>string;advanceTime?:(ms:number)=>void;}}
export async function createWorld(canvas:HTMLCanvasElement,onHud:(hud:WorldHud)=>void,onInteract:(id:string)=>void):Promise<WorldApi>{
 const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;
 const scene=new THREE.Scene();scene.background=new THREE.Color('#c7cec7');scene.fog=new THREE.Fog('#c7cec7',42,110);
 const camera=new THREE.PerspectiveCamera(25,1,.1,180);const ambient=new THREE.HemisphereLight('#dce5fc','#756591',1.4);scene.add(ambient);
 const sun=new THREE.DirectionalLight('#ffe2b4',2.2);sun.position.set(-18,34,16);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-42,right:42,top:42,bottom:-42,near:1,far:110});sun.shadow.normalBias=.035;sun.shadow.bias=-.0004;scene.add(sun);
 const env=await makeEnvironment(scene,Math.min(8,renderer.capabilities.getMaxAnisotropy()));const physics=await createVehiclePhysics(env.obstacles,undefined,env.groundPhysics);
 // Canvas antialiasing does not cover offscreen postprocessing targets.
 const target=new THREE.WebGLRenderTarget(1,1,{type:THREE.HalfFloatType,samples:Math.min(4,renderer.capabilities.maxSamples)});
 const composer=new EffectComposer(renderer,target);composer.addPass(new RenderPass(scene,camera));const bloom=new UnrealBloomPass(new THREE.Vector2(1000,800),.25,.55,.82);composer.addPass(bloom);
 // Preserve fine grass, lettering and silhouettes instead of blurring the screen.
 composer.addPass(new OutputPass());
 let low=false,night=false,paused=false,showcase:string|null=null,zoom=28,time=0,frame=0,last=performance.now(),lastHud=0,accumulator=0,manualUntil=0,disposed=false;
 let careerReading:number|null=null,activeCareer:number|null=null;
 const raycaster=new THREE.Raycaster();
 const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
 let touch:Input={throttle:0,steer:0,brake:false};const keys=new Set<string>();let car=physics.read(),nearby:string|null=null;
 const center=new THREE.Vector3(car.x,0,car.z),look=new THREE.Vector3(),desiredCam=new THREE.Vector3();const pan=new THREE.Vector2();let panDrag:{id:number;x:number;y:number;lastX:number;lastY:number;moved:boolean}|null=null;
 let audio:AudioContext|null=null,osc:OscillatorNode|null=null,gain:GainNode|null=null,sound=false;
 const initAudio=()=>{if(audio)return;audio=new AudioContext();osc=audio.createOscillator();gain=audio.createGain();osc.type='triangle';osc.frequency.value=46;gain.gain.value=0;osc.connect(gain).connect(audio.destination);osc.start();};
 const resize=()=>{const w=Math.max(1,canvas.clientWidth),h=Math.max(1,canvas.clientHeight);const dpr=low?1:Math.min(devicePixelRatio,2);renderer.setPixelRatio(dpr);renderer.setSize(w,h,false);composer.setPixelRatio(dpr);composer.setSize(w,h);camera.aspect=w/Math.max(1,h);camera.updateProjectionMatrix();if(low)renderer.render(scene,camera);else composer.render();};const observer=new ResizeObserver(resize);observer.observe(canvas);resize();
 const stateInput=():Input=>({throttle:THREE.MathUtils.clamp((keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0)+touch.throttle,-1,1),steer:THREE.MathUtils.clamp((keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+touch.steer,-1,1),brake:keys.has('KeyB')||keys.has('ControlLeft')||touch.brake});
 function step(dt:number){time+=dt;if(!paused){let input=stateInput();if(keys.has('ShiftLeft'))input={...input,throttle:input.throttle*1.5};physics.step(input,dt,keys.has('Space'));car=physics.read();if(car.y< -3||Math.abs(car.x)>75||Math.abs(car.z)>75)reset();if(input.throttle||input.steer)pan.multiplyScalar(.97);}
  env.car.position.set(car.x,car.y,car.z);env.car.quaternion.copy(car.rotation);
  env.wheels.forEach((wheel,i)=>{const anchor=WHEEL_ANCHORS[i],info=car.wheels[i];wheel.pivot.position.set(anchor.x,anchor.y-info.length,anchor.z);wheel.pivot.rotation.y=info.steering;if(wheel.rolling)wheel.rolling.rotation.z-=car.speed*dt/.39;});
  env.update(time,new THREE.Vector3(car.x,0,car.z),car.speed,night);
  activeCareer=paused?null:findNearbyCareer(car,activeCareer);env.career.update(time,activeCareer);
  const focus=careerReading!==null?env.career.focus(careerReading):showcase?env.screenGroups.get(showcase):null;
  if(focus){look.copy(focus.focus);desiredCam.copy(focus.camera);const offset=desiredCam.clone().sub(look);const fit=(careerReading!==null?5.6:11.2)/(2*Math.tan(THREE.MathUtils.degToRad(camera.fov/2))*camera.aspect)*1.12;desiredCam.copy(look).add(offset.normalize().multiplyScalar(Math.max(careerReading!==null?14:19.7,fit)));if(careerReading!==null&&(innerWidth>760||(innerWidth>innerHeight&&innerHeight<=520))){const shift=new THREE.Vector3(2,0,-1);look.add(shift);desiredCam.add(shift);}}
  else {center.lerp(new THREE.Vector3(car.x,0,car.z),1-Math.exp(-7*dt));look.set(center.x+pan.x,.45,center.z+pan.y);const radius=zoom+Math.min(Math.abs(car.speed)*.3,3)+(camera.aspect<.8?10:0);const theta=Math.PI/4,phi=Math.PI*.31;desiredCam.set(look.x+radius*Math.sin(phi)*Math.sin(theta),look.y+radius*Math.cos(phi),look.z+radius*Math.sin(phi)*Math.cos(theta));}
  if(reducedMotion)camera.position.copy(desiredCam);else camera.position.lerp(desiredCam,1-Math.exp(-(focus?5:7)*dt));camera.lookAt(look);
  nearby=activeCareer!==null?'career':locations.find(p=>Math.hypot(p.x-car.x,p.z-car.z)<3.6)?.id??null;
  if(audio&&gain&&osc){gain.gain.setTargetAtTime(sound&&!paused?.003+Math.abs(car.speed)*.001:0,audio.currentTime,.1);osc.frequency.setTargetAtTime(42+Math.abs(car.speed)*6,audio.currentTime,.1);}
 }
 function render(){if(low)renderer.render(scene,camera);else composer.render();}
 function hud(now:number){if(now-lastHud<90)return;lastHud=now;const rect=canvas.getBoundingClientRect();onHud({speed:Math.round(Math.abs(car.speed)*3.6),nearby,position:{x:car.x,z:car.z},drivingTo:false,bodyY:car.y,contactCount:car.wheels.filter(w=>w.contact).length,careerIndex:activeCareer,careerLabels:env.career.anchors.map(a=>{const v=a.position.clone().project(camera);return{index:a.index,x:(v.x*.5+.5)*rect.width,y:(-v.y*.5+.5)*rect.height,visible:!paused&&v.z<1&&Math.abs(v.x)<.92&&Math.abs(v.y)<.84&&Math.hypot(a.position.x-car.x,a.position.z-car.z)<20};}),labels:locations.map(p=>{const v=new THREE.Vector3(p.x,.9,p.z).project(camera);return{id:p.id,x:(v.x*.5+.5)*rect.width,y:(-v.y*.5+.5)*rect.height,visible:!showcase&&Math.hypot(p.x-car.x,p.z-car.z)<15&&Math.abs(v.x)<.96&&Math.abs(v.y)<.87};})});}
 function tick(now:number){if(disposed)return;frame=requestAnimationFrame(tick);if(document.hidden){last=now;return;}accumulator+=Math.min((now-last)/1000,.1);last=now;if(now>manualUntil){let steps=0;while(accumulator>=1/60&&steps<6){step(1/60);accumulator-=1/60;steps++;}}else accumulator=0;render();hud(now);}
 const reset=(p:Point={x:0,z:7})=>{careerReading=null;activeCareer=null;env.career.setReading(null);physics.reset(p);car=physics.read();keys.clear();touch={throttle:0,steer:0,brake:false};pan.set(0,0);center.set(car.x,0,car.z);accumulator=0;};
 const blur=()=>{panDrag=null;keys.clear();touch={throttle:0,steer:0,brake:false};physics.stop();car=physics.read();last=performance.now();};
 const keyDown=(e:KeyboardEvent)=>{if(paused||(e.target as HTMLElement)?.closest('input,textarea,[contenteditable="true"],[role="dialog"]'))return;if((e.target as HTMLElement)?.closest('button,a')&&['Space','Enter'].includes(e.code))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.code==='KeyR')reset();if((e.code==='KeyE'||e.code==='Enter')&&nearby&&!e.repeat)onInteract(activeCareer!==null?`career:${activeCareer}`:nearby);};const keyUp=(e:KeyboardEvent)=>keys.delete(e.code);
 const down=(e:PointerEvent)=>{if(paused||e.button!==0)return;if(panDrag){panDrag.moved=true;return;}panDrag={id:e.pointerId,x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false};canvas.setPointerCapture(e.pointerId);};
 const move=(e:PointerEvent)=>{if(!panDrag||panDrag.id!==e.pointerId)return;if(Math.hypot(e.clientX-panDrag.x,e.clientY-panDrag.y)>6)panDrag.moved=true;if(panDrag.moved){const dx=(e.clientX-panDrag.lastX)*.028,dz=(e.clientY-panDrag.lastY)*.035;pan.x-=dx+dz;pan.y+=dx-dz;}panDrag.lastX=e.clientX;panDrag.lastY=e.clientY;};
 const cancel=(e:PointerEvent)=>{if(panDrag?.id===e.pointerId)panDrag=null;};
 const up=(e:PointerEvent)=>{if(!panDrag||panDrag.id!==e.pointerId)return;const tap=!panDrag.moved&&Math.hypot(e.clientX-panDrag.x,e.clientY-panDrag.y)<8;panDrag=null;if(paused||!tap)return;const rect=canvas.getBoundingClientRect();raycaster.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const targets=env.career.targets.filter(object=>{for(let node:THREE.Object3D|null=object;node;node=node.parent)if(!node.visible)return false;return true;});const hit=raycaster.intersectObjects(targets,false)[0];if(hit)onInteract(`career:${hit.object.userData.careerIndex}`);};
 const wheel=(e:WheelEvent)=>{if(paused)return;e.preventDefault();zoom=THREE.MathUtils.clamp(zoom+e.deltaY*.012,21,40);};
 addEventListener('keydown',keyDown);addEventListener('keyup',keyUp);addEventListener('blur',blur);document.addEventListener('visibilitychange',blur);canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',cancel);canvas.addEventListener('lostpointercapture',cancel);canvas.addEventListener('wheel',wheel,{passive:false});
 window.render_game_to_text=()=>JSON.stringify({mode:paused?'reading':'exploring',coordinates:'X east; Z south; +Y up; vehicle faces local -Z',car,input:stateInput(),nearby,showcase,career:{nearby:activeCareer,...env.career.state(),entries:careerEntries.map(e=>({index:e.index,id:e.id,x:e.x,z:e.z}))},quality:low?'low':'high',rendering:{pixelRatio:renderer.getPixelRatio(),canvas:[canvas.width,canvas.height],postprocess:[composer.readBuffer.width,composer.readBuffer.height],samples:low?0:target.samples,anisotropy:Math.min(8,renderer.capabilities.getMaxAnisotropy())},night,audio:{enabled:sound,state:audio?.state??'uninitialized'},view:{position:camera.position.toArray(),focus:look.toArray(),aspect:camera.aspect,width:canvas.clientWidth,height:canvas.clientHeight},locations:locations.map(p=>({id:p.id,x:p.x,z:p.z}))});
 window.advanceTime=(ms:number)=>{manualUntil=performance.now()+120;for(let i=0;i<Math.ceil(ms/(1000/60));i++)step(1/60);render();lastHud=0;hud(performance.now());};
 for(let i=0;i<90;i++)step(1/60);camera.position.copy(desiredCam);camera.lookAt(look);render();frame=requestAnimationFrame(tick);
 return{reset:()=>reset(),goTo:id=>{if(id==='career'){reset({x:careerEntries[0].x,z:-14.5});return;}const p=locations.find(p=>p.id===id);if(!p)return;reset({x:p.x,z:p.z+1.4});},setInput:input=>{if(!paused)touch={...touch,...input};},setPaused:value=>{paused=value;keys.clear();touch={throttle:0,steer:0,brake:false};physics.stop();car=physics.read();},setQuality:value=>{low=value;renderer.shadowMap.enabled=!value;resize();},setNight:value=>{night=value;scene.background=new THREE.Color(value?'#393850':'#c7cec7');scene.fog=new THREE.Fog(value?'#393850':'#c7cec7',42,110);ambient.intensity=value?1.1:1.4;sun.intensity=value?1.4:2.2;sun.color.set(value?'#a8a2ee':'#ffe2b4');},setShowcase:(id,projectId)=>{if(id){careerReading=null;env.career.setReading(null);}showcase=id;if(id&&projectId)void env.setPreview(id,projectId);},setCareer:index=>{careerReading=index===null?null:normalizeCareerIndex(index);env.career.setReading(careerReading);showcase=null;panDrag=null;if(index!==null){paused=true;keys.clear();touch={throttle:0,steer:0,brake:false};physics.stop();car=physics.read();}},setSound:value=>{initAudio();sound=value;if(value)void audio?.resume();},dispose:()=>{disposed=true;cancelAnimationFrame(frame);observer.disconnect();removeEventListener('keydown',keyDown);removeEventListener('keyup',keyUp);removeEventListener('blur',blur);document.removeEventListener('visibilitychange',blur);canvas.removeEventListener('pointerdown',down);canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);canvas.removeEventListener('pointercancel',cancel);canvas.removeEventListener('lostpointercapture',cancel);canvas.removeEventListener('wheel',wheel);physics.free();env.dispose();composer.dispose();renderer.dispose();void audio?.close();delete window.render_game_to_text;delete window.advanceTime;}};
}
